apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.onUninstallKeep }}
    helm.sh/resource-policy: "keep"
  {{- end }}
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "helm-secret.fullname" $)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- range $key, $val := .Values.data }}
  {{- $secretVal := ($val | b64enc) }}
  {{- if empty $secretVal }}
  {{- $secretVal = (get $secretData $key) | default (randAlphaNum (int $.Values.secretLength) | b64enc) }}
  {{- end }}
  {{ $key }}: {{ $secretVal }}
  {{- end }}
